### PR TITLE
[WIP] Materialize styling

### PR DESCRIPTION
**Pull request by jwashke**
- Changed color scheme to monochrome with teal accent
- changed add to cart button so that it appears regardless of whether card is revealed. I worry previous method of only showing button on reveal provides a barrier to customer purchasing items
- changed cards to size 6 on large screens to give more room for card text and buttons to breathe
- added hover effect to cards
- added dashboard link to navbar for logged in users, autoredirects to admin dashboard if logged in user is admin
- replaced cart text next to cart icon with number showing number of items in cart

Marking this as WIP as nothing is set in stone, just some ideas I had to refactoring style slightly. Let me know what you guys think.

### CODE REVIEW

**Comment by JaredRoth** [comment]
I like it way better than salmon.

But honestly, these are great changes. I especially like the practical inclusions of the cart number and relocation of the add to cart button.

**Comment by JaredRoth** [comment]
I haven't looked at things in a few days, so I'm not sure when this happened. 

Was there a design choice to move the price back to the left of the cards and bring back the three dots on the right? Right now the cards seem very tall (with the inclusion of 'add to cart' at the bottom, which is a good idea) and moving the price back to where the dots are will save us a line and I think keep things consistent since the price is on the right in the cart.

What do you guys think? It's a super easy change, so I was just wondering if it was an intentional choice at some point. Let me know!

**Comment by jwashke** [comment]
That wasn't anything we discussed, i was fighting with materialize a lot, I'm perfectly happy to move the price back to the right side.

**Comment by JaredRoth** [comment]
It looks like the sidebar partial actually contains the entire items index page. Going to test moving the rest of the page back out into the view.

**Comment by JaredRoth** [comment]
This branch is ready to merge to master.
All tests passing - no hound complaints.

When squashing, whoever approves this may want to also remove the reference to the branch merge in addition to all the hound commits. (hash: fed6787)

**Pull request merged**
