### PR TITLE
Implement extensive model testing and factory girl factories

### PR DESCRIPTION
**Pull request by jwashke**
Increased model testing, added association, scope, and enum testing for models
Added factory girl gem and a factory for each database table.

Would like to migrate feature specs to utilize factories. Waiting to do that with confirmation feature specs are hands off to prevent merge conflicts.

### CODE REVIEW

**Comment by JaredRoth** [comment]
I thought there was a way to nest declarations of related "classes" in factory girl?

Something like:

```
  factory :user do
    sequence :email do |n|
      "person#{n}@example.com"
    end
    password "password"
    first_name "Jon"
    last_name "Doe"
    address "123 Fake Street"
    city "faketown"
    state "CA"
    zip "92504"

    factory :admin do
      sequence :email do |n|
        "admin#{n}@example.com"
      end
      role 1
    end

  end
```

I only mention it because I think it helps to reduce some duplication.
"Keepin' it dry"

**Comment by JaredRoth** [comment]
Regarding that previous note: I can totally do that if that's something you guys are interested in having done.

**Comment by jwashke** [comment]
There probably is, I made those pretty quickly while banging out model tests. I certainly prefer DRYness so I can look into changing that or if you want to pull down the branch and submit a PR with your changes that would be cool too.

**Comment by JaredRoth** [comment]
Ok. I'll go ahead and do that and then add that commit to this PR if you guys can wait a few hours. (Memorial service) If you need this branch merged before then, go ahead and I'll just make a new one.

**Comment by jwashke** [comment]
Theres no rush to merge this one so we'll just wait for your commit

**Pull request merged**
