### PR TITLE
User has limits

### LINKED ISSUE #40: Authenticated users security
Background: An authenticated user and the ability to add an admin user
      As an Authenticated User
      I cannot view another user's private data (current or past orders, etc)
      I cannot view the administrator screens or use admin functionality
      I cannot make myself an admin

### LINKED ISSUE #41: Unauthenticated users security
Background: An unauthenticated user and their abilities
      As an Unuthenticated User
      I cannot view another user's private data, such as current order, etc.
      I should be redirected to login/create account when I try to check out.
      I cannot view the administrator screens or use administrator functionality.
      I cannot make myself an administrator.

### LINKED ISSUE #59: logged in user can only view their orders
A logged in user only has access to their own order history

### PR DESCRIPTION
**Pull request by GKhalsa**
add tests for user security 
user can not view admin dashboard 
non logged in user cannot view orders 
one user cannot view another users orders 

closes #40 
closes #41 
closes #59

### CODE REVIEW

**Comment by JaredRoth** [comment]
Since Josh implemented factorygirl, there's now a lot of inconsistency between how we set up our tests. If you guys aren't opposed to it, I can go through and make that swap.

**Comment by JaredRoth** [comment]
On that same note, what about database cleaner? Did you, @jwashke, implement that as well?
(I guess I could just check...)

**Comment by jwashke** [comment]
Yeah I implemented Database Cleaner, I also swapped out all of our helper methods for factory usage. Its in my PR if you want to take a look. Unfortunately I should have made smaller PRs as its all part of a pretty big change where I did some pretty major refactoring. Me and Sunnys PR do the same thing so we should only merge one of them. I guess its on your to decide @JaredRoth

**Comment by JaredRoth** [comment]
Since I'm a little out of the loop overall, it'll probably be best if one of you looks at this. I am not sure if you guys duplicated work or not. One of you could probably tell with a glance...

**Comment by JaredRoth** [comment]
Amendment to previous comment: I _did_ look at it (and resolve merge conflicts), but I don't know what work might have been duplicated.

**Comment by jwashke** [comment]
The other merge made this pr redundant, so I'm going to go ahead and close this one.

**Pull request closed without merging**
